version: "3.8"
services:
  front:
    build: ./
    container_name: node
    command: sh -c 'cd /front && yarn start'
    volumes:
      - ./front:/front
    working_dir: /front
    ports:
      - 3000:3000
    tty: true
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
